name: Test, Build, and Publish Docker Image

on:
  push: # Trigger on pushes to branches
    branches:
      - develop  # Trigger publishing on develop branch only
  pull_request: # Trigger on pull requests for all branches
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1 # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Run tests
      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudsweep:latest .

  publish:
    if: github.ref == 'refs/heads/develop'  # Run only on the develop branch
    runs-on: ubuntu-latest
    needs: test-and-build  # Ensure tests and build pass before publishing

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cloudsweep:latest
